"""Added total_amount row to MonthlyCharge model

Revision ID: 2b4708439d68
Revises: e308959d7ff1
Create Date: 2026-02-25 21:10:59.602710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4708439d68'
down_revision = 'e308959d7ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_charges', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
