"""Added updated_at column to MonthlyChararge model.

Revision ID: 516170dabe58
Revises: f03b1ffb020e
Create Date: 2026-03-05 00:16:10.441119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516170dabe58'
down_revision = 'f03b1ffb020e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_charges', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
