"""Chnaged month in MonthlyCharges from String to Integer as it is using numbers 1-12.

Revision ID: e022c10d3eea
Revises: 516170dabe58
Create Date: 2026-03-08 17:11:10.760067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e022c10d3eea'
down_revision = '516170dabe58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_charges', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_charges', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
