"""Added updated_at column to Occupancy model to handle changes ie. rent changes, early termination, wrong entries etc.

Revision ID: f03b1ffb020e
Revises: 2b4708439d68
Create Date: 2026-03-04 15:22:54.219727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03b1ffb020e'
down_revision = '2b4708439d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancies', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
